name: Call webhook on push

on:
  push:
    branches:
      - main

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook
        run: curl -X POST ${{ secrets.WEBHOOK_URL }}
